definitions:
  rooms.RoomTypeCreate:
    properties:
      bed_count:
        type: integer
      charges_for_cancellation:
        type: number
      food_option:
        type: string
      name:
        type: string
      price:
        type: number
    required:
    - bed_count
    - charges_for_cancellation
    - food_option
    - name
    - price
    type: object
  rooms.RoomTypeUpdate:
    properties:
      bed_count:
        type: integer
      charges_for_cancellation:
        type: number
      food_option:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  users.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  users.UserCreate:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /room-types:
    post:
      consumes:
      - application/json
      description: Create room type
      parameters:
      - description: RoomTypeCreate
        in: body
        name: RoomType
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomTypeCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.RoomTypeCreate'
      summary: Create room type
      tags:
      - room-types
  /room-types/{id}:
    put:
      consumes:
      - application/json
      description: Update room type
      parameters:
      - description: RoomType ID
        in: path
        name: id
        required: true
        type: string
      - description: RoomTypeUpdate
        in: body
        name: RoomType
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomTypeUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.RoomTypeUpdate'
      summary: Update room type
      tags:
      - room-types
  /users:
    get:
      consumes:
      - application/json
      description: Get a list of users with pagination
      parameters:
      - description: Page number (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items per page (default is 10)
        in: query
        name: limit
        type: integer
      - description: Cursor for pagination
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.User'
            type: array
      summary: List users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: UserCreate
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserCreate'
      summary: Create user
      tags:
      - users
swagger: "2.0"
