definitions:
  common.Image:
    properties:
      cloud_name:
        type: string
      extension:
        type: string
      height:
        type: integer
      id:
        type: integer
      url:
        type: string
      width:
        type: integer
    type: object
  rooms.Room:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      images:
        items:
          $ref: '#/definitions/common.Image'
        type: array
      name:
        type: string
      occupancy_status:
        type: string
      roomType:
        $ref: '#/definitions/rooms.RoomType'
      updated_at:
        type: string
    type: object
  rooms.RoomCreate:
    properties:
      description:
        type: string
      images:
        items:
          $ref: '#/definitions/common.Image'
        type: array
      name:
        type: string
      room_type_id:
        type: string
    required:
    - name
    - room_type_id
    type: object
  rooms.RoomType:
    properties:
      bed_count:
        type: integer
      charges_for_cancellation:
        type: number
      food_option:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  rooms.RoomTypeCreate:
    properties:
      bed_count:
        type: integer
      charges_for_cancellation:
        type: number
      food_option:
        type: string
      name:
        type: string
      price:
        type: number
    required:
    - bed_count
    - charges_for_cancellation
    - food_option
    - name
    - price
    type: object
  rooms.RoomTypeResponse:
    properties:
      bed_count:
        type: integer
      charges_for_cancellation:
        type: number
      food_option:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  rooms.RoomTypeUpdate:
    properties:
      bed_count:
        type: integer
      charges_for_cancellation:
        type: number
      food_option:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  rooms.RoomUpdate:
    properties:
      description:
        type: string
      images:
        items:
          $ref: '#/definitions/common.Image'
        type: array
      name:
        type: string
      room_type_id:
        type: string
    type: object
  users.User:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  users.UserCreate:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /room-types:
    get:
      consumes:
      - application/json
      description: List room types
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rooms.RoomTypeResponse'
            type: array
      summary: List room types
      tags:
      - room-types
    post:
      consumes:
      - application/json
      description: Create room type
      parameters:
      - description: RoomTypeCreate
        in: body
        name: RoomType
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomTypeCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.RoomTypeCreate'
      summary: Create room type
      tags:
      - room-types
  /room-types/{id}:
    get:
      consumes:
      - application/json
      description: Get room type
      parameters:
      - description: RoomType ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.RoomTypeResponse'
      summary: Get room type
      tags:
      - room-types
    put:
      consumes:
      - application/json
      description: Update room type
      parameters:
      - description: RoomType ID
        in: path
        name: id
        required: true
        type: string
      - description: RoomTypeUpdate
        in: body
        name: RoomType
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomTypeUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.RoomTypeUpdate'
      summary: Update room type
      tags:
      - room-types
  /rooms:
    get:
      consumes:
      - application/json
      description: Get rooms
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Cursor
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rooms.Room'
      summary: Get rooms
      tags:
      - rooms
    post:
      consumes:
      - application/json
      description: Create room
      parameters:
      - description: RoomCreate
        in: body
        name: Room
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rooms.RoomCreate'
            type: array
      summary: Create room
      tags:
      - rooms
  /rooms/{id}:
    put:
      consumes:
      - application/json
      description: Update room
      parameters:
      - description: Room ID
        in: path
        name: id
        required: true
        type: string
      - description: RoomUpdate
        in: body
        name: Room
        required: true
        schema:
          $ref: '#/definitions/rooms.RoomUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update room
      tags:
      - rooms
  /users:
    get:
      consumes:
      - application/json
      description: Get a list of users with pagination
      parameters:
      - description: Page number (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of items per page (default is 10)
        in: query
        name: limit
        type: integer
      - description: Cursor for pagination
        in: query
        name: cursor
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.User'
            type: array
      summary: List users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: UserCreate
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/users.UserCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserCreate'
      summary: Create user
      tags:
      - users
swagger: "2.0"
